@echo off
setlocal
if "%WORKER_EPISODE_QUEUE_NAME%"=="" set "WORKER_EPISODE_QUEUE_NAME=episode-jobs-hunyuan-sidecar"
set "VIDEO_HUNYUAN_PREMIUM_DEFAULT=false"
set "VIDEO_SIDECAR_BENCHMARK_FAST_MODE=false"
set "BENCHMARK_PRESET_FAST_MODE=false"
set "VIDEO_SIDECAR_PREMIUM_CANDIDATE_COUNT=1"
set "VIDEO_SIDECAR_PREMIUM_ACTUAL_CANDIDATE_COUNT=1"
set "VIDEO_SIDECAR_PREMIUM_ACTUAL_RETAKE_COUNT=0"
set "VIDEO_HUNYUAN_COMFY_TIMEOUT_MS=10800000"
set "VIDEO_HUNYUAN_SR_COMFY_TIMEOUT_MS=21600000"
set "VIDEO_HUNYUAN_SR_TILED_VAE_DECODE=true"
node scripts\runWorkerDirect.mjs
